set lines 300 pages 100
col username for a30
select username from dba_users
where username not in ('ANONYMOUS','APPQOSSYS','AUDSYS','BAASSYS','CTXSYS',',DBSFWUSER','DBSNMP','DGPDB_INT','DIP','DVF','DVSYS','GGSHAREDCAP','GGSYS','GSMADMIN_INTERNAL','GSMCATUSER','GSMROOTUSER','GSMUSER','LBACSYS','MSQL> DDATA','MDSYS','OJVMSYS','OLAPSYS','OPS$ORACLE','OUTLN','REMOTE_SCHEDULER_AGENT','SYS','SYS$UMF','SYSBACKUP','SYSDG','SYSKM','SYSRAC','SYSTEM','VECSYS','WMSYS','XDB','XS$NULL','MDDA