#!/bin/bash
# script to create an oracle listener

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration – override these via environment variables or edit directly
# ---------------------------------------------------------------------------
ORACLE_HOME="${ORACLE_HOME:-/u01/app/oracle/product/19c/dbhome_1}"
ORACLE_BASE="${ORACLE_BASE:-/u01/app/oracle}"
LISTENER_NAME="${LISTENER_NAME:-LISTENER}"
LISTENER_PORT="${LISTENER_PORT:-1521}"
LISTENER_HOST="${LISTENER_HOST:-$(hostname -f 2>/dev/null || hostname)}"
ORACLE_SID="${ORACLE_SID:-ORCL}"
LISTENER_ORA="${ORACLE_HOME}/network/admin/listener.ora"
TNSNAMES_ORA="${ORACLE_HOME}/network/admin/tnsnames.ora"

export ORACLE_HOME ORACLE_BASE ORACLE_SID
PATH="${ORACLE_HOME}/bin:${PATH}"

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------
log()  { echo "[INFO]  $(date '+%Y-%m-%d %H:%M:%S') $*"; }
warn() { echo "[WARN]  $(date '+%Y-%m-%d %H:%M:%S') $*" >&2; }
die()  { echo "[ERROR] $(date '+%Y-%m-%d %H:%M:%S') $*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------
[[ -d "${ORACLE_HOME}" ]] || die "ORACLE_HOME not found: ${ORACLE_HOME}"
command -v lsnrctl &>/dev/null  || die "lsnrctl not found – check ORACLE_HOME/PATH"
[[ -n "${LISTENER_NAME}" ]] || die "LISTENER_NAME must not be empty"
[[ -n "${ORACLE_SID}" ]] || die "ORACLE_SID must not be empty"
[[ "${LISTENER_PORT}" =~ ^[0-9]+$ ]] || die "LISTENER_PORT must be numeric: ${LISTENER_PORT}"

# ---------------------------------------------------------------------------
# Build listener.ora
# ---------------------------------------------------------------------------
log "Writing listener configuration to ${LISTENER_ORA}"
mkdir -p "$(dirname "${LISTENER_ORA}")"

cat > "${LISTENER_ORA}" <<EOF
# Generated by create_listener.sh on $(date)

${LISTENER_NAME} =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = ${LISTENER_HOST})(PORT = ${LISTENER_PORT}))
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC_FOR_${LISTENER_NAME}))
    )
  )

SID_LIST_${LISTENER_NAME} =
  (SID_LIST =
    (SID_DESC =
      (GLOBAL_DBNAME = ${ORACLE_SID})
      (ORACLE_HOME   = ${ORACLE_HOME})
      (SID_NAME      = ${ORACLE_SID})
    )
  )

LOGGING_${LISTENER_NAME}    = ON
LOG_DIRECTORY_${LISTENER_NAME}  = ${ORACLE_BASE}/diag/tnslsnr/$(hostname -s)/${LISTENER_NAME,,}/alert
TRACE_LEVEL_${LISTENER_NAME}    = OFF
EOF

# ---------------------------------------------------------------------------
# Append tnsnames.ora entry (idempotent – removes old entry first)
# ---------------------------------------------------------------------------
log "Updating ${TNSNAMES_ORA}"
touch "${TNSNAMES_ORA}"

# Remove previous entry for this SID if it exists
if awk -v sid="${ORACLE_SID}" '
  BEGIN { found = 0 }
  {
    line = $0
    sub(/^[[:space:]]+/, "", line)
    if (index(line, sid) == 1) {
      rest = substr(line, length(sid) + 1)
      if (rest ~ /^[[:space:]]*=/) {
        found = 1
        exit 0
      }
    }
  }
  END { exit(found ? 0 : 1) }
' "${TNSNAMES_ORA}" 2>/dev/null; then
    warn "Existing entry for ${ORACLE_SID} found in tnsnames.ora – replacing it"
    # Remove the block belonging to this SID (simple single-entry removal)
    tns_dir="$(dirname -- "${TNSNAMES_ORA}")"
    if original_mode="$(stat -c '%a' "${TNSNAMES_ORA}" 2>/dev/null)"; then
      :
    elif original_mode="$(stat -f '%Lp' "${TNSNAMES_ORA}" 2>/dev/null)"; then
      :
    else
      die "Failed to determine permissions for ${TNSNAMES_ORA}"
    fi
    tmp_tns="$(umask 077 && mktemp "${tns_dir}/.tnsnames.tmp.XXXXXX")" || die "Failed to create temporary file for ${TNSNAMES_ORA}"
    trap 'rm -f "${tmp_tns:-}"' EXIT INT TERM
    awk -v sid="${ORACLE_SID}" '
      BEGIN { skip = 0 }
      {
        line = $0
        trimmed = line
        sub(/^[[:space:]]+/, "", trimmed)
        if (!skip && index(trimmed, sid) == 1) {
          rest = substr(trimmed, length(sid) + 1)
          if (rest ~ /^[[:space:]]*=/) {
            skip = 1
            next
          }
        }
        if (skip) {
          # TNS aliases are expected at column 1, e.g. ORCL =
          if (line ~ /^[[:alnum:]_][[:alnum:]_.-]*[[:space:]]*=/) {
            skip = 0
          } else {
            next
          }
        }
        print line
      }
    ' "${TNSNAMES_ORA}" > "${tmp_tns}"
    mv "${tmp_tns}" "${TNSNAMES_ORA}" || die "Failed to update ${TNSNAMES_ORA}"
    chmod "${original_mode}" "${TNSNAMES_ORA}" || die "Failed to restore permissions on ${TNSNAMES_ORA}"
    trap - EXIT INT TERM
fi

cat >> "${TNSNAMES_ORA}" <<EOF

${ORACLE_SID} =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = ${LISTENER_HOST})(PORT = ${LISTENER_PORT}))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = ${ORACLE_SID})
    )
  )
EOF

# ---------------------------------------------------------------------------
# Stop any running instance of this listener, then start fresh
# ---------------------------------------------------------------------------
if lsnrctl status "${LISTENER_NAME}" &>/dev/null; then
    log "Stopping existing listener '${LISTENER_NAME}'"
    lsnrctl stop "${LISTENER_NAME}" || warn "Could not stop listener gracefully"
fi

log "Starting listener '${LISTENER_NAME}'"
lsnrctl start "${LISTENER_NAME}" || die "Failed to start listener '${LISTENER_NAME}'"

log "Listener status:"
lsnrctl status "${LISTENER_NAME}"

log "Done. Listener '${LISTENER_NAME}' is running on ${LISTENER_HOST}:${LISTENER_PORT}"
