set lines 300 pages 100
col name for a20

SELECT 
  NAME, 
  SCN, 
  TIME, 
  DATABASE_INCARNATION#,
  GUARANTEE_FLASHBACK_DATABASE,
  STORAGE_SIZE/1024/1024/1024 STORAGE_SIZE_GB
FROM 
  V$RESTORE_POINT
WHERE 
  GUARANTEE_FLASHBACK_DATABASE='YES';