-- 1. Stop managed recovery
ALTER DATABASE RECOVER MANAGED STANDBY DATABASE CANCEL;

-- 2. Open standby in read-only mode
ALTER DATABASE OPEN;

-- 3. Restart recovery in real-time
ALTER DATABASE RECOVER MANAGED STANDBY DATABASE USING CURRENT LOGFILE DISCONNECT FROM SESSION;
