SET LINESIZE 200
SET PAGESIZE 100

PROMPT == Database Role & Status ==
SELECT DATABASE_ROLE, OPEN_MODE, PROTECTION_MODE, PROTECTION_LEVEL 
FROM V$DATABASE;

PROMPT == Archive Log Mode ==
SELECT LOG_MODE, FORCE_LOGGING, SWITCHOVER_STATUS 
FROM V$DATABASE;

PROMPT == Redo Transport Configuration ==
SELECT DEST_ID, STATUS, DESTINATION, ARCHIVER, TRANSMIT_MODE, AFFIRM, SYNC_STATUS, VALID_NOW 
FROM V$ARCHIVE_DEST_STATUS 
WHERE DEST_ID > 1;

PROMPT == Standby Database Information ==
SELECT THREAD#, SEQUENCE#, APPLIED, FIRST_TIME, NEXT_TIME 
FROM V$ARCHIVED_LOG 
WHERE DEST_ID = 2 
ORDER BY SEQUENCE# DESC FETCH FIRST 5 ROWS ONLY;

PROMPT == Data Guard Configuration Details ==
SELECT PROPERTY_NAME, PROPERTY_VALUE 
FROM DATABASE_PROPERTIES 
WHERE PROPERTY_NAME LIKE 'DG%';

PROMPT == Data Guard Process Monitoring ==
SELECT PROCESS, STATUS, SEQUENCE# 
FROM V$MANAGED_STANDBY 
WHERE PROCESS IN ('RFS', 'MRP0', 'LNS');

PROMPT == Log Shipping Gap Detection ==
SELECT THREAD#, MAX(SEQUENCE#) AS LAST_SENT 
FROM V$ARCHIVED_LOG 
WHERE DEST_ID = 2 
GROUP BY THREAD#;

SELECT THREAD#, MAX(SEQUENCE#) AS LAST_APPLIED 
FROM V$ARCHIVED_LOG 
WHERE APPLIED = 'YES' 
GROUP BY THREAD#;

PROMPT == Checking Lag Between Primary and Standby ==
SELECT NAME, VALUE FROM V$DATAGUARD_STATS;

PROMPT == Data Guard Broker Configuration (If Enabled) ==
SELECT * FROM V$DG_BROKER_CONFIG;